#!/bin/bash
# If error of bash : Bad Substitution, because using dash bash
# curl -s https://raw.githubusercontent.com/raultm/amade/master/amade | sudo bash
IMAGE_SELECTED=$(whiptail --clear --backtitle "Amade" --title "Images" --menu "Choose:" 20 80 10 `for x in $(ls  /home/partimag/); do echo $x "-"; done` 3>&1 1>&2 2>&3)
#echo "Selected image: " $IMAGE_SELECTED

DISKS_SELECTED=$(whiptail --clear --backtitle "Amade" --title "Disks" --checklist "Choose disks:" 20 80 10 `for x in $(find /dev/sd*  -printf "%f "); do echo $x "-" off; done` 3>&1 1>&2 2>&3)
DISKS_SELECTED=$(eval echo ${DISKS_SELECTED[@]})
#echo "Selected disks: " ${DISKS_SELECTED[@]}

# Option (https://gist.github.com/gotbletu/630478ddf5b4e6ad6abd1a8b23918830)
# -g auto     | Install grub in the MBR of the disk containing partition GRUB_PARTITION
# -e1 auto    | Force to change the CHS (cylinders, heads, sectors) value of NTFS boot partition after image is restored.
# -e2         | Force to use the CHS (cylinders, heads, sectors) from EDD (Enhanced Disk Device) when creating partition table by sfdisk
# -r          | Resize the partition when restoration finishes, this will resize the file system size to fit the partition size.
# -j2         | Use dd to clone the image of the data between MBR (1st sector, i.e. 512 bytes) and 1st partition, which might be useful for some recovery tool.
# -batch      | (DANGEROUS!) Run program in batch mode, i.e. without any prompt or wait for pressing enter key.
# -scr        | By default Clonezilla will check the image if restorable before restoring. This option allows you to skip that.
# -p poweroff | When save/restoration finishes, choose action in the client, poweroff, reboot (default), in command prompt or run CMD
echo "/usr/sbin/ocs-sr -g auto -e1 auto -e2 -r -j2 -batch -scr -p poweroff restoredisk $IMAGE_SELECTED ${DISKS_SELECTED[@]}"
/usr/sbin/ocs-sr -g auto -e1 auto -e2 -r -j2 -batch -scr -p poweroff restoredisk $IMAGE_SELECTED ${DISKS_SELECTED[@]}
